version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customers
      PGDATA: /.data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - '5432'

  postgres-test:
    image: postgres:alpine
    restart: always
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customers_test
      PGDATA: /.data/postgres_test
    ports:
      - "15432:5432"
    volumes:
      - ./.data/postgres_test:/data/postgres_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - '15432'

networks:
  default:
